version: '3'

services:
  nginx:
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile 
    image: my_nginx
    ports:
      - "443:443"
    volumes:
      - wordpresssssss:/var/www/html/
    restart: always
    networks:
      - worknet
    depends_on:
      - wordpress

  wordpress:
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    image: my_wordpress
    volumes:
      - wordpresssssss:/var/www/html
    restart: always
    networks:
      - worknet
    depends_on:
      - mariadb

  mariadb:
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    image: my_mariadb
    volumes:
      - maria_databaseeeee:/var/lib/mysql
    restart: always
    networks:
      - worknet

volumes:
  maria_databaseeeee:
    name: maria_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/hasalam/Desktop/maria_database
  wordpresssssss:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/hasalam/Desktop/wordpress

networks:
  worknet:
    driver: bridge